/*
 * Projeto de conclusão das disciplinas de BD e POO (Ciência da Computação/IFNMG).
 */
package br.edu.ifnmg.rockinrio.gui;

import br.edu.ifnmg.rockinrio.dao.EspectadorDao;
import br.edu.ifnmg.rockinrio.entity.Endereco;
import br.edu.ifnmg.rockinrio.entity.Espectador;
import java.time.LocalDate;

public class CadastroEspectadorDialog extends javax.swing.JDialog {

    /**
     * cadastroIngresso vai guardar uma referência a janela de Ingressos que a
     * abriu para compartilhamento de informações.
     * atributo Novo identifica se será a criação de um espectador ou a 
     * edição do mesmo
     * eSeçecionado guarda uma referência ao espectador escolhido no ComboList
     * de ingressos.
     */
    CadastroIngressoDialog cadastroIngresso;
    Boolean novo;
    Espectador eSelecionado;

    public CadastroEspectadorDialog(CadastroIngressoDialog cadastroIngresso, Boolean novo) {
        super(cadastroIngresso, true);

        this.cadastroIngresso = cadastroIngresso;
        this.novo = novo;

        initComponents();

        txtCpf.setEditable(novo);
    }

    public CadastroEspectadorDialog(CadastroIngressoDialog cadastroIngresso,
            Boolean novo, Espectador eSelecionado) {
        super(cadastroIngresso, true);

        this.cadastroIngresso = cadastroIngresso;
        this.novo = novo;
        this.eSelecionado = eSelecionado;

        initComponents();
        initCampos();
        txtCpf.setEditable(novo);
    }

    /**
     * Método que obtém as informações dos campos do formulário para a criação
     * de um objeto do tipo Espectador para ser persistido no banco de dados.
     * há uma diferença de execução dependendo do tipo de serviço solicitado
     * se é a criação ou edição de um espectador, que será distinguível através
     * do atributo "novo"
     */
    private void salvarEspectador() {

        int codigo;
        if(novo){
            codigo = EspectadorDao.obterProximoCodigo();
        }else{
            codigo = eSelecionado.getCodigo();
        }
        String cpf = txtCpf.getText();
        String nome = txtNome.getText();
        String tipoPessoa = "Espectador";
        LocalDate dataNascimento = LocalDate.parse(txtDataNascimento.getText());
        String cep = txtCep.getText();
        String bairro = txtBairro.getText();
        String rua = txtRua.getText();
        int numero = Integer.parseInt(txtNumero.getText());

        Endereco endereco = new Endereco(
                cep,
                bairro,
                rua,
                numero
        );

        Espectador espectador = new Espectador(
                codigo,
                cpf,
                nome,
                tipoPessoa,
                dataNascimento,
                endereco
        );

        if (novo) {
            EspectadorDao.inserir(espectador);
        } else {
            EspectadorDao.atualizar(espectador);
        }

        /**
         * atualiza o Menu Combo Espectador da janela de criação de ingressos.
         */
        cadastroIngresso.initCmbEspectador();

        dispose();
    }

    /**
     * Caso este dialog tenha sido chamado para edição de um Espectador já
     * existente, preencher seus dados nos campos para alteração.
     */
    private void initCampos() {
        txtCpf.setText(eSelecionado.getCpf());
        txtNome.setText(eSelecionado.getNome());
        txtDataNascimento.setText(eSelecionado.getDataNascimento().toString());
        txtCep.setText(eSelecionado.getEndereco().getCep());
        txtBairro.setText(eSelecionado.getEndereco().getBairro());
        txtRua.setText(eSelecionado.getEndereco().getRua());
        txtNumero.setText(eSelecionado.getEndereco().getNumero().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastroEspectador = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        lblPrincipal = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCpf.setText("CPF");

        lblNome.setText("Nome");

        lblDataNascimento.setText("Data de Nascimento");

        txtDataNascimento.setText("2001-01-01");

        lblCep.setText("Cep");

        lblBairro.setText("Bairro");

        lblRua.setText("Rua");

        lblNumero.setText("Numero");

        separador.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPrincipal.setText("Cadastro de Espectador");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroEspectadorLayout = new javax.swing.GroupLayout(pnlCadastroEspectador);
        pnlCadastroEspectador.setLayout(pnlCadastroEspectadorLayout);
        pnlCadastroEspectadorLayout.setHorizontalGroup(
            pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroEspectadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroEspectadorLayout.createSequentialGroup()
                .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCadastroEspectadorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroEspectadorLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCadastroEspectadorLayout.createSequentialGroup()
                                .addComponent(lblDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCadastroEspectadorLayout.createSequentialGroup()
                                .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCpf)
                                    .addComponent(lblNome))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCpf)
                                    .addGroup(pnlCadastroEspectadorLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(55, 55, 55)
                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCep)
                            .addComponent(lblBairro)
                            .addComponent(lblRua)
                            .addComponent(lblNumero))))
                .addGap(28, 28, 28)
                .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCep, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRua)
                    .addComponent(txtNumero))
                .addContainerGap())
        );
        pnlCadastroEspectadorLayout.setVerticalGroup(
            pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroEspectadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrincipal)
                .addGap(35, 35, 35)
                .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCadastroEspectadorLayout.createSequentialGroup()
                        .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCpf))
                        .addGap(20, 20, 20)
                        .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataNascimento)
                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCadastroEspectadorLayout.createSequentialGroup()
                        .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCep))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBairro))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRua))
                        .addGap(23, 23, 23)
                        .addGroup(pnlCadastroEspectadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero)))
                    .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadastroEspectador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlCadastroEspectador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        salvarEspectador();
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPrincipal;
    private javax.swing.JLabel lblRua;
    private javax.swing.JPanel pnlCadastroEspectador;
    private javax.swing.JSeparator separador;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
