/*
 * Projeto de conclusão das disciplinas de BD e POO (Ciência da Computação/IFNMG).
 */
package br.edu.ifnmg.rockinrio.gui;

import br.edu.ifnmg.rockinrio.dao.OcorrenciaDao;
import br.edu.ifnmg.rockinrio.entity.Ocorrencia;
import javax.swing.DefaultListModel;
import java.awt.event.MouseEvent;

public class GerenciamentoOcorrencias extends javax.swing.JFrame {

    // TODO - Criar painel de login e obter o CPF a partir dele.
    private final String cpfProfissionalLogado = "54079310530";
    
    private DefaultListModel<Ocorrencia> ocorrenciasEditaveis;
    private DefaultListModel<Ocorrencia> ocorrenciasLeitura;
    private int indiceOcorrenciaEditavelSelecionada;
    private int indiceOcorrenciaLeituraSelecionada;
    
    public GerenciamentoOcorrencias() {
        initDados();
        initComponents();
    }
    
    private void initDados() {
        ocorrenciasEditaveis = new DefaultListModel<>();
        ocorrenciasLeitura = new DefaultListModel<>();
        
        var ocorrencias = OcorrenciaDao.obterTodos();
        
        ocorrencias.forEach(ocorrencia -> {
            if (cpfProfissionalLogado.equals(ocorrencia.getCpfProfissionalSeguranca())) {
                ocorrenciasEditaveis.addElement(ocorrencia);
            }
            else {
                ocorrenciasLeitura.addElement(ocorrencia);
            }
        });
        
        // TODO - Inserir o nome do profissional de usuário no campo "Usuário: __________".
    }
    
    public void inserirOcorrenciaNaLista(Ocorrencia ocorrencia) {
        ocorrenciasEditaveis.addElement(ocorrencia);
    }
    
    public void atualizarOcorrenciaNaLista(Ocorrencia ocorrencia) {
        ocorrenciasEditaveis.set(indiceOcorrenciaEditavelSelecionada, ocorrencia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpMenuEditaveis = new javax.swing.JPopupMenu();
        menuItemDetalhesE = new javax.swing.JMenuItem();
        menuItemEditar = new javax.swing.JMenuItem();
        menuItemExcluir = new javax.swing.JMenuItem();
        popUpMenuLeitura = new javax.swing.JPopupMenu();
        menuItemDetalhesL = new javax.swing.JMenuItem();
        painelPrincipal = new javax.swing.JPanel();
        retornarMenuPrincipal = new javax.swing.JLabel();
        buttonRetornarMenuPrincipal = new javax.swing.JButton();
        tituloPrincipal = new javax.swing.JLabel();
        nomeUsuarioLogado = new javax.swing.JLabel();
        registradasPorVoce = new javax.swing.JLabel();
        scrollPanelOcorrenciasEditaveis = new javax.swing.JScrollPane();
        listaOcorrenciasEditaveis = new javax.swing.JList<>();
        porOutrosProfissionais = new javax.swing.JLabel();
        scrollPanelOcorrenciasLeitura = new javax.swing.JScrollPane();
        listaOcorrenciasLeitura = new javax.swing.JList<>();
        buttonRegistrarNovaOcorrencia = new javax.swing.JButton();

        menuItemDetalhesE.setMnemonic('d');
        menuItemDetalhesE.setText("Detalhes");
        menuItemDetalhesE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDetalhesEActionPerformed(evt);
            }
        });
        popUpMenuEditaveis.add(menuItemDetalhesE);

        menuItemEditar.setMnemonic('e');
        menuItemEditar.setText("Editar");
        menuItemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditarActionPerformed(evt);
            }
        });
        popUpMenuEditaveis.add(menuItemEditar);

        menuItemExcluir.setMnemonic('x');
        menuItemExcluir.setText("Excluir");
        popUpMenuEditaveis.add(menuItemExcluir);

        menuItemDetalhesL.setMnemonic('d');
        menuItemDetalhesL.setText("Detalhes");
        menuItemDetalhesL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDetalhesLActionPerformed(evt);
            }
        });
        popUpMenuLeitura.add(menuItemDetalhesL);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rock In Rio - Gerenciamento de Ocorrências");
        setName("frm-gerenciamento-ocorrencias"); // NOI18N
        setResizable(false);

        retornarMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        retornarMenuPrincipal.setText("Retornar ao menu principal");

        buttonRetornarMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonRetornarMenuPrincipal.setText("<");
        buttonRetornarMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetornarMenuPrincipalActionPerformed(evt);
            }
        });

        tituloPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tituloPrincipal.setText("Gerenciamento de ocorrências");

        nomeUsuarioLogado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nomeUsuarioLogado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nomeUsuarioLogado.setText("Usuário: _______________________");

        registradasPorVoce.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        registradasPorVoce.setText("Registradas por você:");

        listaOcorrenciasEditaveis.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        listaOcorrenciasEditaveis.setModel(ocorrenciasEditaveis);
        listaOcorrenciasEditaveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listaOcorrenciasEditaveisMouseReleased(evt);
            }
        });
        scrollPanelOcorrenciasEditaveis.setViewportView(listaOcorrenciasEditaveis);

        porOutrosProfissionais.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        porOutrosProfissionais.setText("Por outros profissionais:");

        listaOcorrenciasLeitura.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        listaOcorrenciasLeitura.setModel(ocorrenciasLeitura);
        listaOcorrenciasLeitura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listaOcorrenciasLeituraMouseReleased(evt);
            }
        });
        scrollPanelOcorrenciasLeitura.setViewportView(listaOcorrenciasLeitura);

        buttonRegistrarNovaOcorrencia.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonRegistrarNovaOcorrencia.setText("Registrar Nova Ocorrência");
        buttonRegistrarNovaOcorrencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRegistrarNovaOcorrenciaMouseReleased(evt);
            }
        });
        buttonRegistrarNovaOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarNovaOcorrenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addComponent(buttonRetornarMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retornarMenuPrincipal)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addComponent(tituloPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomeUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registradasPorVoce)
                    .addComponent(buttonRegistrarNovaOcorrencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPanelOcorrenciasEditaveis, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(porOutrosProfissionais)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollPanelOcorrenciasLeitura, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRetornarMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retornarMenuPrincipal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloPrincipal)
                    .addComponent(nomeUsuarioLogado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registradasPorVoce)
                    .addComponent(porOutrosProfissionais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(scrollPanelOcorrenciasEditaveis, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRegistrarNovaOcorrencia))
                    .addComponent(scrollPanelOcorrenciasLeitura)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistrarNovaOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarNovaOcorrenciaActionPerformed
        
    }//GEN-LAST:event_buttonRegistrarNovaOcorrenciaActionPerformed

    private void buttonRetornarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetornarMenuPrincipalActionPerformed
        
    }//GEN-LAST:event_buttonRetornarMenuPrincipalActionPerformed

    private void listaOcorrenciasEditaveisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaOcorrenciasEditaveisMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON3 && listaOcorrenciasEditaveis.getModel().getSize() > 0) {
            indiceOcorrenciaEditavelSelecionada = listaOcorrenciasEditaveis.locationToIndex(evt.getPoint());
            listaOcorrenciasEditaveis.setSelectedIndex(indiceOcorrenciaEditavelSelecionada);
            popUpMenuEditaveis.show(listaOcorrenciasEditaveis, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_listaOcorrenciasEditaveisMouseReleased

    private void listaOcorrenciasLeituraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaOcorrenciasLeituraMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON3 && listaOcorrenciasLeitura.getModel().getSize() > 0) {
            indiceOcorrenciaLeituraSelecionada = listaOcorrenciasLeitura.locationToIndex(evt.getPoint());
            listaOcorrenciasLeitura.setSelectedIndex(indiceOcorrenciaLeituraSelecionada);
            popUpMenuLeitura.show(listaOcorrenciasLeitura, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_listaOcorrenciasLeituraMouseReleased

    private void menuItemDetalhesEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDetalhesEActionPerformed
        Ocorrencia ocorrenciaSelecionada = listaOcorrenciasEditaveis.getSelectedValue();
        
        if (ocorrenciaSelecionada == null) {
            var mensagemErroDialog = new MensagemErroDialog(this, "Não foi possível realizar a ação.");
            mensagemErroDialog.setLocationRelativeTo(this);
            mensagemErroDialog.setVisible(true);
        }
        else {
            String mensagem =
                  "- Número: " + ocorrenciaSelecionada.getNumero() + "\n"
                + "- Data: " + ocorrenciaSelecionada.getDataOcorrenciaEmString(true) + "\n"
                + "- CPF do profissional de segurança: " 
                + ocorrenciaSelecionada.getCpfProfissionalSeguranca() + "\n"
                + "- CPF da pessoa: " + ocorrenciaSelecionada.getCpfPessoa() + "\n"
                + "- Nome da pessoa: " + ocorrenciaSelecionada.getNomePessoa() + "\n"
                + "- Descrição: " + ocorrenciaSelecionada.getDescricao() + "\n"
                + "- Longitude: " + ocorrenciaSelecionada.getLongitude() + "\n"
                + "- Latitude: " + ocorrenciaSelecionada.getLatitude();
            
            var mensagemDialog =
                new MensagemGenericaDialog(this, "Detalhes da Ocorrência", "Detalhes da Ocorrência", mensagem);
            mensagemDialog.setLocationRelativeTo(this);
            mensagemDialog.setVisible(true);
        }
    }//GEN-LAST:event_menuItemDetalhesEActionPerformed

    private void menuItemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarActionPerformed
        var edicaoOcorrenciaDialog = 
            new EdicaoOcorrenciaDialog(this, listaOcorrenciasEditaveis.getSelectedValue());
        edicaoOcorrenciaDialog.setLocationRelativeTo(this);
        edicaoOcorrenciaDialog.setVisible(true);
    }//GEN-LAST:event_menuItemEditarActionPerformed

    private void menuItemDetalhesLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDetalhesLActionPerformed
        Ocorrencia ocorrenciaSelecionada = listaOcorrenciasLeitura.getSelectedValue();
        
        if (ocorrenciaSelecionada == null) {
            var mensagemErroDialog = new MensagemErroDialog(this, "Não foi possível realizar a ação.");
            mensagemErroDialog.setLocationRelativeTo(this);
            mensagemErroDialog.setVisible(true);
        }
        else {
            String mensagem =
                  "- Número: " + ocorrenciaSelecionada.getNumero() + "\n"
                + "- Data: " + ocorrenciaSelecionada.getDataOcorrenciaEmString(true) + "\n"
                + "- CPF do profissional de segurança: " 
                + ocorrenciaSelecionada.getCpfProfissionalSeguranca() + "\n"
                + "- CPF da pessoa: " + ocorrenciaSelecionada.getCpfPessoa() + "\n"
                + "- Nome da pessoa: " + ocorrenciaSelecionada.getNomePessoa() + "\n"
                + "- Descrição: " + ocorrenciaSelecionada.getDescricao() + "\n"
                + "- Longitude: " + ocorrenciaSelecionada.getLongitude() + "\n"
                + "- Latitude: " + ocorrenciaSelecionada.getLatitude();
            
            var mensagemDialog =
                new MensagemGenericaDialog(this, "Detalhes da Ocorrência", "Detalhes da Ocorrência", mensagem);
            mensagemDialog.setLocationRelativeTo(this);
            mensagemDialog.setVisible(true);
        }
    }//GEN-LAST:event_menuItemDetalhesLActionPerformed

    private void buttonRegistrarNovaOcorrenciaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegistrarNovaOcorrenciaMouseReleased
        var cadastroOcorrenciaDialog = 
            new CadastroOcorrenciaDialog(this, cpfProfissionalLogado);
        cadastroOcorrenciaDialog.setLocationRelativeTo(this);
        cadastroOcorrenciaDialog.setVisible(true);
    }//GEN-LAST:event_buttonRegistrarNovaOcorrenciaMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoOcorrencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoOcorrencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoOcorrencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoOcorrencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoOcorrencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegistrarNovaOcorrencia;
    private javax.swing.JButton buttonRetornarMenuPrincipal;
    private javax.swing.JList<Ocorrencia> listaOcorrenciasEditaveis;
    private javax.swing.JList<Ocorrencia> listaOcorrenciasLeitura;
    private javax.swing.JMenuItem menuItemDetalhesE;
    private javax.swing.JMenuItem menuItemDetalhesL;
    private javax.swing.JMenuItem menuItemEditar;
    private javax.swing.JMenuItem menuItemExcluir;
    private javax.swing.JLabel nomeUsuarioLogado;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPopupMenu popUpMenuEditaveis;
    private javax.swing.JPopupMenu popUpMenuLeitura;
    private javax.swing.JLabel porOutrosProfissionais;
    private javax.swing.JLabel registradasPorVoce;
    private javax.swing.JLabel retornarMenuPrincipal;
    private javax.swing.JScrollPane scrollPanelOcorrenciasEditaveis;
    private javax.swing.JScrollPane scrollPanelOcorrenciasLeitura;
    private javax.swing.JLabel tituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
