/*
 * Projeto de conclusão das disciplinas de BD e POO (Ciência da Computação/IFNMG).
 */
package br.edu.ifnmg.rockinrio.gui;

import br.edu.ifnmg.rockinrio.dao.IngressoDao;
import br.edu.ifnmg.rockinrio.entity.Ingresso;
import javax.swing.DefaultListModel;

/**
 *
 * @author Anderson Gomes
 */
public class GerenciamentoIngressosDialog extends javax.swing.JDialog {

    
    private DefaultListModel<Ingresso> lstIngressosModel;
    /**
     * Creates new form GerenciamentoIngressosDialog
     */
    public GerenciamentoIngressosDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        lstIngressosModel = new DefaultListModel<>();
        
        var ingressos = IngressoDao.obterTodos();
        
        lstIngressosModel.addAll(ingressos);
        
        initComponents();
    }
    
    public void inserirIngressoNaLista(Ingresso ingresso){
        lstIngressosModel.addElement(ingresso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIngressos = new javax.swing.JPanel();
        lblIngressos = new javax.swing.JLabel();
        scrLstIngressos = new javax.swing.JScrollPane();
        lstIngressos = new javax.swing.JList<>();
        btnCadastrar = new javax.swing.JButton();
        buttonRetornarMenuPrincipal = new javax.swing.JButton();
        retornarMenuPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblIngressos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblIngressos.setText("Ingressos");

        lstIngressos.setModel(lstIngressosModel);
        scrLstIngressos.setViewportView(lstIngressos);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        buttonRetornarMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonRetornarMenuPrincipal.setText("<");
        buttonRetornarMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRetornarMenuPrincipalMouseReleased(evt);
            }
        });
        buttonRetornarMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetornarMenuPrincipalActionPerformed(evt);
            }
        });

        retornarMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        retornarMenuPrincipal.setText("Retornar ao menu principal");

        javax.swing.GroupLayout pnlIngressosLayout = new javax.swing.GroupLayout(pnlIngressos);
        pnlIngressos.setLayout(pnlIngressosLayout);
        pnlIngressosLayout.setHorizontalGroup(
            pnlIngressosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngressosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIngressosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngressosLayout.createSequentialGroup()
                        .addComponent(buttonRetornarMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(retornarMenuPrincipal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(scrLstIngressos, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIngressosLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
            .addGroup(pnlIngressosLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lblIngressos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlIngressosLayout.setVerticalGroup(
            pnlIngressosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngressosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIngressosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRetornarMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retornarMenuPrincipal))
                .addGap(3, 3, 3)
                .addComponent(lblIngressos)
                .addGap(18, 18, 18)
                .addComponent(scrLstIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlIngressos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlIngressos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        var cadastroIngresso = new CadastroIngressoDialog(this, true);
        cadastroIngresso.setLocationRelativeTo(this);
        cadastroIngresso.setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void buttonRetornarMenuPrincipalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRetornarMenuPrincipalMouseReleased
        dispose();
    }//GEN-LAST:event_buttonRetornarMenuPrincipalMouseReleased

    private void buttonRetornarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetornarMenuPrincipalActionPerformed

    }//GEN-LAST:event_buttonRetornarMenuPrincipalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton buttonRetornarMenuPrincipal;
    private javax.swing.JLabel lblIngressos;
    private javax.swing.JList<Ingresso> lstIngressos;
    private javax.swing.JPanel pnlIngressos;
    private javax.swing.JLabel retornarMenuPrincipal;
    private javax.swing.JScrollPane scrLstIngressos;
    // End of variables declaration//GEN-END:variables
}
